- project/CommonSettings.scala
- project/Dependencies.scala
- src/main/scala/play/api/db/slick/ddl/ReflectionUtils.scala
- src/main/scala/play/api/db/slick/ddl/TableScanner.scala
Since Play master has upgraded to reflections 0.9.9, this breaks when building play-slick against it due to binary incompatible changes in reflections.
> Upgraded to reflections 0.9.9

- README.md
- project/Dependencies.scala
* The link to the latest Play Slick doc in the README is currently broken. It will work as soon as the documentation in this repo is aggregated with the Play 2.4 doc (which should happen soon enough).
> Update readme and slick version

- src/main/scala/play/api/db/slick/DbName.scala
- src/main/scala/play/api/db/slick/package.scala
Omnidoc nightly compilation is failing with this:
```
[error] /home/play/deploy/omnidoc/target/scala-2.10/omnidoc/sources/com.typesafe.play-play-slick_2.10-0.9.0-2015-04-30-90781ab-SNAPSHOT/play/api/db/slick/DatabaseConfigProvider.scala:81: type mismatch;
[error]  found   : play.api.db.slick.play.api.db.slick.DbName
[error]  required: play.api.db.slick.(some other)play.api.db.slick.DbName
[error]       slickApi.dbConfig[P](DbName(dbName))
[error]                                  ^
[error] /home/play/deploy/omnidoc/target/scala-2.10/omnidoc/sources/com.typesafe.play-play-slick_2.10-0.9.0-2015-04-30-90781ab-SNAPSHOT/play/api/db/slick/SlickApi.scala:54: type mismatch;
[error]  found   : scala.collection.generic.CanBuildFrom[Any,Char,String]
[error]  required: …
```
> Omnidoc failure

- src/core/src/main/scala/play/api/db/slick/SlickApi.scala
This is a small change needed to compile the codebase with Slick 3.1.0-M1.
Without this change, scalac was reporting the following error:
parameter 'config' is already specified at parameter position 2
This may be a compiler bug, as it is quite similar to SI-8117 \cc @lrytz
@adriaanm
> Project compiles against Slick 3.1.0-M1

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickMigrationGuide.md
I assume you meant in implements the specification, rather than the SPI, which I believe refers to the _Special Interest Group_ for Reactive Streams? (or did you mean API)?
> (docs) replace 'SPI' with 'specification'

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickMigrationGuide.md
Thanks all who ported my sample project here to the new Reactive Streams system. It really makes it a lot easier to understand the changes. Especially thanks for keeping the test working.
> (docs typo: 'projet' -> 'project')

- src/evolutions/src/main/scala/play/api/db/slick/evolutions/internal/DBApiAdapter.scala
Hi,
I used the `leakDetectionThreshold` parameter of Hikari to debug this one. Here is the output : 
```
2015-07-29 11:13:07,158 - WARN  com.zaxxer.hikari.pool.LeakTask: Connection leak detection triggered for connection org.postgresql.jdbc4.Jdbc4Connection@4a452d73, stack trace follows
java.lang.Exception: Apparent connection leak detected
at slick.jdbc.HikariCPJdbcDataSource.createConnection(JdbcDataSource.scala:131) ~[slick_2.11-3.0.0.jar:na]
at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394) ~[slick_2.11-3.0.0.jar:na]
at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:394) ~[slick_2.11-3.0.0.jar:na]
at slick.jdbc.JdbcBackend$BaseSession.metaData$lzycompute(JdbcBackend.scala:395) ~[slick_2.11-3.0.0.jar:na]
at …
```
> Fix connection leak when using Play-Evolution

- project/Dependencies.scala
Because HikariCP doesn't yet guarantee binary compatibility of its releases (see
brettwooldridge/HikariCP#360), it's safer that play-slick uses the exact same
version of HikariCP used to compile Slick 3.0 (which is currently v2.3.7).
Furthermore, Slick 3 uses the HikariCP-java6 binaries, while in play-slick we
were using the HikariCP binaries for Java8. While this shouldn't create problems
(because the two releases are built from the same tag - see
https://groups.google.com/forum/#!topic/hikari-cp/MqCtC4RQdeA), it's once again
safer to use the same binaries used by Slick.
\cc @szeiger
> HikariCP version matches the one used in Slick 3.0

- samples/iteratee/build.sbt
- samples/iteratee/conf/application-test.conf
This is an attempt to fix the spurious test failure happening when
running the iteratee-sample IntegrationSpec test.
> Use a larger connection timeout for iteratee-sample tests. Fix #297

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickMigrationGuide.md
Due to the trailing dollar sign of the newly introduced application config value, slick.driver.H2Driver$, an IDE complains that such characters as $ are prohibited in application.conf. This is a tiny fix for this issue.
> Wrapping the config value slick.driver.H2Driver$ with double quotes

- version.sbt
As it will take a while before Slick 3.2 M1 will be published, separating
development for play-slick 1.1.x and 1.2.x is not worth at the moment. Hence,
this commit changes the master version back to 1.1.0-SNAPSHOT and we can remove
the 1.1.x branch.
> Setting master version to 1.1.0-SNAPSHOT

- src/core/src/test/scala/play/api/db/slick/SlickApiSpec.scala
- src/core/src/test/scala/play/api/db/slick/TestData.scala
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/internal/DBApiAdapter.scala
- src/evolutions/src/test/scala/play/api/db/slick/evolutions/DBApiAdapterSpec.scala
In play-slick 1.0.x we were using the connection's metadata to retrieve the
database's url. In play-slick 1.1.x we have tried to use the Slick database's
config, but the implementation didn't consider datasource's config, as the
stacktrace in the related ticket demonstrates.
The fix simply consisted in reintroducing the former, play-slick 1.0.x,
behavior, as it seemed to have been working just fine so far.
> Correctly reading the database's url from a datasource's config. Fix #324

- build.sbt
When updating interplay to 1.1.0 (see 7655ac1cb4ef561bae7659e1d6a17865d790ef0c),
I've forgot to bump the Scala version to 2.11.7 in the project's sample
factory.
> Bumped Scala version to 2.11.7 in sample projects. Fix #332

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickFAQ.md
Fixes #357. Also replaced some Typesafe mentions with Lightbend.
[One URL left with a TODO](358/files#diff-6e12c50e78295138ed776e6a5e042d46R136), because I don't know where it should point to.
> Fix typos && broken URLs in docs, add a few missing "the"s

- docs/manual/working/scalaGuide/main/sql/slick/code/DI.scala
- docs/manual/working/scalaGuide/main/sql/slick/code/GlobalLookup.scala
- docs/manual/working/scalaGuide/main/sql/slick/code/UsersSchema.scala
This is a follow up for #370. It removes deprecated api usage from documentation code.
> Remove deprecation from guide code

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
- docs/manual/working/scalaGuide/main/sql/slick/code/DI.scala
- docs/manual/working/scalaGuide/main/sql/slick/code/GlobalLookup.scala
References to Play.current are currently deprecated, and in play-slick 2.0.x referencing slick 3.1, JdbcProfile was moved to the slick.driver package from slick.jdbc
> Updated documentation for play-slick usage

- src/evolutions/src/main/scala/play/api/db/slick/evolutions/EvolutionsModule.scala
- src/evolutions/src/test/scala/play/api/db/slick/evolutions/EvolutionsModuleSpec.scala
If I try to implement an application loader with components class for compile-time DI and want to mixin `SlickEvolutionsComponents` trait (together with `SlickComponents` which contains the actual implementation of `slickApi`) to it, I am getting the following compile error:
```
class Components inherits conflicting members:
[error]   lazy value slickApi in trait SlickComponents of type play.api.db.slick.SlickApi  and
[error]   method slickApi in trait SlickEvolutionsComponents of type => play.api.db.slick.SlickApi
[error] (Note: this can be resolved by declaring an override in class Components.)
[error] class Components(context: ApplicationLoader.Context)
```
A workaround for it is to override `slickApi` again in components class, but it's ugly:
```
override lazy val slickApi: SlickApi = …
```
> slickApi must be abstract in SlickEvolutionsComponents

- README.md
- project/Dependencies.scala
slick 3.2.1 fixes race-condition using unpinned/flatMapped DBIOActions, leading to missing decreaseInUseCount calls and possible stall of ManagedBlockingArrayQueue
https://github.com/slick/slick/issues/1730
> Update to slick 3.2.1 -> propose play-slick plugin release of 2.1.1

- src/core/src/main/scala/play/api/db/slick/DatabaseConfigProvider.scala
The filed `dbConfig` should be lazy to avoid early initialization problems.
In my particular case I have a class:
`class SomeDAO @Inject()(protected val dbConfigProvider: DatabaseConfigProvider) extends HasDatabaseConfigProvider[JdbcProfile] { ... }`
that needs to be mocked and the eager initialization makes the mock fail with a 
`java.lang.NullPointerException
at play.api.db.slick.HasDatabaseConfigProvider$class.$init$(DatabaseConfigProvider.scala:196)`
> this field should be lazy to avoid early initialization problems.

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
Since this page appears on https://www.playframework.com/documentation/2.6.x/PlaySlick it is a tad confusing when it says it only supports Play 2.5 and Slick 3.1.
> Update docs to reflect latest Play+Slick version

- src/core/src/main/scala/play/api/db/slick/SlickModule.scala
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/EvolutionsModule.scala
Fixes #422, closes #423 
This field make SlickComponents incompatible with macwire, there's no
way to keep it around without providing a bad user experience for people
using compile time dependency injection with macwire.
> Delete deprecated SlickComponents.api field

- .travis.yml
A lot of people will instantly migrate to Scala 2.12.7 because it has a lot of performance improvements.
More info: https://github.com/scala/scala/releases/tag/v2.12.7
> Add latest scala 2.12.7 to travis builds

- project/Dependencies.scala
3.2.2 and 3.2.3 include several bugfixes, including for concurrency
bugs.
http://slick.lightbend.com/news/2018/03/06/slick-3.2.2-released.html
http://slick.lightbend.com/news/2018/03/23/slick-3.2.3-released.html
> Upgrade slick 3.2.{1 => 3}

- README.md
It seems this github project no longer has a wiki, so any links are fwd to the github project homepage
> Remove wiki reference

- src/core/src/main/scala/play/api/db/slick/DatabaseConfigProvider.scala
Otherwise scaladoc will complain in Scala 2.13.6
See https://github.com/scala/scala/pull/9336
Happened to me when I wanted to bump to Scala 2.13.7 in omnidoc:
https://github.com/playframework/omnidoc/pull/186
```
[error] /home/travis/build/playframework/omnidoc/target/scala-2.13/omnidoc/sources/com.typesafe.play-play-slick_2.13-5.0.0/play/api/db/slick/DatabaseConfigProvider.scala:95:100: annotation argument needs to be a constant; found: scala.Predef.augmentString("Use DatabaseConfigProvider#get[P] or SlickApi#dbConfig[P](\"default\") on injected instances").stripMargin
[error]     "Use DatabaseConfigProvider#get[P] or SlickApi#dbConfig[P](\"default\") on injected instances".stripMargin,
[error] …
```
> @deprecated annotation needs to be constant

- build.sbt
- project/CommonSettings.scala
https://github.com/sbt/sbt/commit/e6fec6b1db5f212a74bf5e3766b9b70f2d983f24
https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
> use new slash syntax instead of deprecated `in`

- samples/basic/app/controllers/Application.scala
- samples/computer-database/app/controllers/Application.scala
- src/core/src/test/scala/play/api/db/slick/SlickApiSpec.scala
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/internal/DBApiAdapter.scala
```
[warn] /home/travis/build/playframework/play-slick/src/core/src/test/scala/play/api/db/slick/SlickApiSpec.scala:51:20: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method dbConfigs,
[warn] or remove the empty argument list from its definition (Java-defined methods are exempt).
[warn] In Scala 3, an unapplied method like this will be eta-expanded into a function.
[warn]       api.dbConfigs[BasicProfile] must have size 4
[warn]                    ^
[warn] /home/travis/build/playframework/play-slick/src/core/src/test/scala/play/api/db/slick/SlickApiSpec.scala:55:20: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method dbConfigs,
[warn] or remove the empty argument list from its …
```
> fix `Auto-application` warnings

- .scalafmt.conf
- CONTRIBUTING.md
- README.md
- RELEASING.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
@SethTisue and @ihostage already renamed the `master` branch in some play repos:
* https://github.com/playframework/cachecontrol/pull/163
* https://github.com/playframework/play-file-watch/pull/136
* https://github.com/playframework/play-json/pull/598
* https://github.com/playframework/play-soap/pull/282
* https://github.com/playframework/play-ws/pull/597
* https://github.com/playframework/twirl/pull/416
Now that we are centralising configs in the [`.github`](https://github.com/playframework/.github) repo it's a good idea that all repos have the same default branch name.
To change to `main` locally (if the remote to this repo is called `upstream`):
```sh
git branch -m master main # rename master to main (actually "move")
git fetch upstream
git branch -u upstream/main main # set upstream …
```
> Rename master branch to main

- .github/settings.yml
- .gitignore
- .scalafmt.conf
- CONTRIBUTING.md
- README.md
- RELEASING.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
> [5.0.x] Rename master branch to main

- project/build.properties
- project/plugins.sbt
Again, the same old story... Watiting for sbt 1.8 with "correct" scala version and scala-xml dependency
> Revert "Workaround scala-xml conflicts"

- build.sbt
- src/core/src/main/scala/play/api/db/slick/DatabaseConfigProvider.scala
However since in Scala 2 "lazy values may not be abstract" we need to make it non-abstract with ???. Not the nicest thing to do, but ok...
The reason why I want to get rid of `-source:3.0-migration` is because https://github.com/playframework/omnidoc tries to generate scaladocs from play-slick and to do that for Scala 3 we need to actually compile the sources. Now when adding `-source:3.0-migration` in omnidoc a lot of other compiler errors occur from other classes (that are not part of play-slick)
> Make dbConfig lazy to fix Scala 3 error

- .github/workflows/build-test.yml
- README.md
- build.sbt
- project/Dependencies.scala
Play Slick v6.0 branch currently depends on 3.5.0-M4.
At the moment it seems difficult to estimate when Slick v3.5 will be released.
Play Slick v6 branch however contains very valuable changes, in particular support for Play v3.0 which would allow many users to transition to Play v3.0.
Please consider downgrading to Slick v3.4.1 and releasing v6.0 as is.
> Downgrade to Slick v3.4.1, so that Play v3 based version can be released

- .github/workflows/build-test.yml
- README.md
- build.sbt
- project/Dependencies.scala
> [5.2.x] Use stable slick 3.4 and drop out-of-the-box Scala 3 support for now

- build.sbt
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
- Fixes #826
- See https://github.com/slick/slick/releases/tag/v3.5.0
> slick 3.5.0 final release + other dependency upgrades

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickFAQ.md
Can't crawl, 404:
- https://www.playframework.com/documentation/3.0.x/AccessingAnSqlDatabase
- Correct: https://www.playframework.com/documentation/2.8.x/AccessingAnSQLDatabase
> Fix typo in link

- .scalafmt.conf
- src/core/src/main/scala/play/api/db/slick/SlickApi.scala
- src/core/src/main/scala/play/api/db/slick/SlickModule.scala
- src/core/src/test/scala/play/api/db/slick/DefaultSlickApiSpec.scala
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/EvolutionsModule.scala
old wildcard syntax `[_]` is deprecated in latest Scala 3.
```
Welcome to Scala 3.6.3 (21.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
scala> val a: List[_] = Nil
1 warning found
-- Warning: --------------------------------------------------------------------
1 |val a: List[_] = Nil
|            ^
|        `_` is deprecated for wildcard arguments of types: use `?` instead
val a: List[?] = List()
scala> val b: List[?] = Nil
val b: List[?] = List()
```
> update `.scalafmt.conf`. enforce new wildcard syntax
