- samples/basic/build.sbt
- samples/basic/conf/routes
- samples/computer-database/build.sbt
- samples/dao/build.sbt
- samples/iteratee/app/views/index.scala.html
- samples/json/build.sbt
- samples/json/conf/routes
Fostering Play 2.4 best practices in the sample projects.
> Small clean-up in sample projects' build.sbt and conf files

- version.sbt
The doc has already been updated to reflect this change in the PR #239.
> Bumped version to 1.0.0-SNAPSHOT

- project/Dependencies.scala
- project/Publish.scala
- project/Release.scala
- project/plugins.sbt
- src/test/scala/play/api/db/slick/DatabaseConfigProviderSpec.scala
Also upgraded to Play 2.4.0-RC2
> Use sonatype plugin

- .travis.yml
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickFAQ.md
* Also ensured docs validation runs in travis
* Also configured ivy caching in travis
> Changed link to API to normal link

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickAdvancedTopics.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickMigrationGuide.md
* Better explanation for how to configure the connection pool.
* Some other small improvement.
> Improved documentation based on community feedback

- samples/di/app/dao/DogDAO.scala
> Change parameter name to match parameter type

- src/evolutions/src/main/scala/play/api/db/slick/evolutions/EvolutionsModule.scala
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/SlickDBApi.scala
- src/evolutions/src/test/scala/play/api/db/slick/evolutions/EvolutionsModuleSpec.scala
I added `SlickEvolutionsTrait` and factory method for `DBApi` into evolutions plugin, so it'll possible to use slick-evolutions with compile-time dependency injection.
> #269 Slick evolutions with compile-time DI

- project/Dependencies.scala
- src/core/src/test/scala/play/api/db/slick/TestData.scala
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/internal/DBApiAdapter.scala
- src/evolutions/src/test/scala/play/api/db/slick/evolutions/DBApiAdapterSpec.scala
See #283 for the issue that this fixes.
> Propagate autocommit for evolutions

- project/Dependencies.scala
Stefan Zeiger just released it : http://slick.typesafe.com/news/2015/08/06/slick-3.0.1-released.html
> Upgrade Slick to 3.0.1

- README.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
Please, don't merge this PR just yet. I'll do it when 1.0.1 is about to be released.
> Better README and updated plugin's version in both doc and README

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
merging `master` branch into `1.1.x`
> Merge/master in 1.1.x

- README.md
- project/Dependencies.scala
- samples/computer-database/app/dao/ComputersDAO.scala
Preparing 1.1.0-RC1 release for Slick 3.1.0-RC1.
> Preparing 1.1.0-RC1 release for Slick 3.1.0-RC1

- README.md
- project/Dependencies.scala
Preparing 1.1.0-RC2 release for Slick 3.1.0-RC2
> Preparing 1.1.0-RC2 release for Slick 3.1.0-RC2

- project/Dependencies.scala
Preparing 1.1.0-RC3 release for Slick 3.1.0-RC3
> Preparing 1.1.0-RC3 release for Slick 3.1.0-RC3

- build.sbt
> Set used MiMa base version to 1.1.0. Fix #323

- README.md
- build.sbt
- project/plugins.sbt
- samples/iteratee/build.sbt
Made necessary changes to release play-slick 2.0.0-M1 for Play 2.5.0-M1
> Preparing release

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
> Updated doc and README with latest released version.

- README.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlickMigrationGuide.md
- Changed the current version
- Changed the Migration guide to respect 2.5
- Changed the Documentation to respect 2.5
- Changed the License to Lightbend
> Updated the Readme to respect Play 2.5

- build.sbt
- src/core/src/test/scala/play/api/db/slick/DefaultSlickApiSpec.scala
> Add scala 2.12

- project/Dependencies.scala
- project/plugins.sbt
- src/core/src/test/scala/play/api/db/slick/DatabaseConfigProviderSpec.scala
Bumped slick / play versions, ran tests
> bump versions for play and slick

- src/core/src/main/scala/play/api/db/slick/SlickModule.scala
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/EvolutionsModule.scala
- src/evolutions/src/test/scala/play/api/db/slick/evolutions/EvolutionsModuleSpec.scala
Fix https://github.com/playframework/play-slick/issues/382
> Fix ambiguous/unclear property

- .travis.yml
- README.md
- build.sbt
- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
- docs/manual/working/scalaGuide/main/sql/slick/code/DI.scala
- docs/manual/working/scalaGuide/main/sql/slick/code/GlobalLookup.scala
- docs/manual/working/scalaGuide/main/sql/slick/code/slick.sbt
- project/build.properties
- project/plugins.sbt
- samples/basic/app/controllers/Application.scala
- samples/basic/app/dao/CatDAO.scala
- samples/basic/app/dao/DogDAO.scala
- samples/computer-database/app/bootstrap/InitialData.scala
- samples/computer-database/app/controllers/Application.scala
- samples/computer-database/app/dao/CompaniesDAO.scala
- samples/computer-database/app/dao/ComputersDAO.scala
- samples/computer-database/app/views/list.scala.html
1. Disable filters plugin
2. Reformat sample code and remove deprecations
3. Update releases table
> Update play to M4 version

- docs/manual/working/scalaGuide/main/sql/slick/code/DI.scala
- samples/basic/conf/application.conf
- samples/computer-database/app/views/list.scala.html
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/internal/DBApiAdapter.scala
Backports #408 to branch 3.0.x.
> Fix small problems with sample projects (#408)

- docs/manual/working/scalaGuide/main/sql/slick/code/DI.scala
- samples/basic/conf/application.conf
- samples/computer-database/app/views/list.scala.html
- src/evolutions/src/main/scala/play/api/db/slick/evolutions/internal/DBApiAdapter.scala
> close connection after transaction

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
See https://github.com/playframework/playframework.com/issues/167
> Update outdated configuration

- .travis.yml
- project/build.properties
> Build using AdoptOpenJDK 8 & 11 (#453)

- docs/manual/working/scalaGuide/main/sql/slick/PlaySlick.md
- docs/manual/working/scalaGuide/main/sql/slick/code/slick.sbt
https://github.com/playframework/play-slick/issues/460
> Slick 3.3.0 (doc issue)

- .travis.yml
- project/plugins.sbt
Some other minor build details.
> Update play to version 2.8.0-M5

- .mergify.yml
* use merge
* remove 'smart' merge
* add rule for scala-steward
> Mergify aligment

- samples/computer-database/app/dao/ComputersDAO.scala
- samples/streams/app/models/Record.scala
> add explicit type annotations for implicit val

- .scalafmt.conf
- build.sbt
- docs/build.sbt
- docs/manual/working/scalaGuide/main/sql/slick/code/DI.scala
- docs/manual/working/scalaGuide/main/sql/slick/code/Example.scala
- project/CommonSettings.scala
- project/Dependencies.scala
- src/core/src/main/scala/play/api/db/slick/DatabaseConfigProvider.scala
- src/core/src/main/scala/play/api/db/slick/SlickApi.scala
Fix #648 
Update scalafmt to 3.3.3.
Because of some changes in settings and behavior, I get some diffs when reformatting.
> Scalafmt 3.3.3

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
- build.sbt
- project/plugins.sbt
See https://github.com/slick/slick/pull/2557
> Drop Java 8

- .github/workflows/build-test.yml
> [5.1.x] Semantic Scala version selector expression in workflows

- project/Dependencies.scala
- project/plugins.sbt
Need to pull in play core because of https://github.com/playframework/playframework/pull/10997
> Play 2.9.0-M3 / Fix dependency tree

- build.sbt
- project/Common.scala
- project/Omnidoc.scala
- project/Playdoc.scala
- project/plugins.sbt
As part of https://github.com/playframework/interplay/issues/150
Publishing works fine https://github.com/playframework/play-slick/actions/runs/6162582075/job/16724374806
> Drop interplay

- build.sbt
same as
- https://github.com/playframework/playframework/pull/12029 and
- https://github.com/playframework/scalatestplus-play/pull/458
> remove `-Xmigration`

- .github/workflows/build-test.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/publish.yml
- .github/workflows/release-drafter.yml
- README.md
- build.sbt
- docs/manual/working/scalaGuide/main/sql/slick/code/slick.sbt
- project/Dependencies.scala
> [5.2.x] Slick 3.5.0-RC1 + Scala 3 support 

- .github/workflows/build-test.yml
- README.md
- build.sbt
- docs/manual/working/scalaGuide/main/sql/slick/code/slick.sbt
- project/Dependencies.scala
Waiting for a stable slick 3.5 release...
TODO:
> Slick 3.5.0-RC1 + Scala 3 support

- build.sbt
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
> [5.3.x] slick 3.5.0 final release + other dependency upgrades

- .github/scala-steward.conf
> [6.0.x] Pin slick to version 3.4.x

- .github/scala-steward.conf
> [5.3.x] Scala Steward: Pin dependencies

- src/core/src/main/scala/play/api/db/slick/SlickApi.scala
This resolves https://github.com/playframework/play-slick/issues/348#issuecomment-183367870 out of the box.
> Set unique poolName based on database name

- .github/scala-steward.conf
> [5.2.x] Pin dependencies

- src/core/src/main/scala/play/api/db/slick/DatabaseConfigProvider.scala
- src/core/src/main/scala/play/api/db/slick/SlickModule.scala
prepare latest Scala 3.x
- https://github.com/scala/scala3/pull/22441
- https://github.com/scala/scala3/pull/21257
> add `using` clause
